language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.3
  - android-24
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

script:
  # Unit Test
  - ./gradlew test jacocoTestDebugUnitTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)